WIP: Facesubsystem examples plus bs
jimmy-jam/arfoundation-samples pull request #1
Opened 2018-12-07 19:31 UTC by jimmy-jam

Since I already have a PR for facesubsystem examples, this just shows the diff between that and the blendshapes examples additions.

2018-12-07 19:31 UTC, jimmy-jam commented
depends on https://github.com/Unity-Technologies/upm-xr-arkit/pull/26

2018-12-07 21:32 UTC, tdmowrer requested changes

2018-12-07 21:32 UTC, tdmowrer commented on Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs
> +public class ARFaceArkitBlendShapeVisualizer : MonoBehaviour
This class should conform to the coding conventions:
- No public fields, please (`[SerializedField]` with public getter/setter if you want it to be part of the Editor).
- Public properties don't _require_ documentation, but it would be nice.

2018-12-07 21:32 UTC, tdmowrer commented on Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs
> +
Extra line

2018-12-07 21:32 UTC, tdmowrer commented on Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs
> +    void CreateFeatureBlendMapping()
Seems like this should be a map from `XRArkitBlendShapeLocation` to blend shape index in the mesh renderer. This would save you having to construct a string and look up its index for every blend shape every time the face updates (which could be every frame I'm guessing).

2018-12-07 21:43 UTC, jimmy-jam commented on Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs
> +    void CreateFeatureBlendMapping()
this makes it flexible for people to change the mesh and iterate on it.  if we just wanted to use the index, we could use the XRArkitBlendShapeLocation as the blendshape index.

2018-12-07 22:11 UTC, tdmowrer commented on Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs
> +    void CreateFeatureBlendMapping()
I see how it would make it easier to test out different ideas, but I'm worried this will set a bad example -- most people will start by copying and pasting this into their own code, so the example we provide should be performant. The way it is now will generate tons of garbage each frame.

2018-12-07 22:50 UTC, jimmy-jam commented on Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs
> +    void CreateFeatureBlendMapping()
i would take convenience over premature optimization, but ok.

2018-12-08 00:19 UTC, tdmowrer commented on Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs
> +    void CreateFeatureBlendMapping()
If string names are easier to work with, that's fine. I just mean that the lookup, i.e., 
```csharp
skinnedMeshRenderer.sharedMesh.GetBlendShapeIndex (strPrefix + mappedBlendShapeName);
```

should only happen once at the beginning.

2018-12-08 02:03 UTC, jimmy-jam commented on Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs
> +    void CreateFeatureBlendMapping()
ya i just realized that would hit both our reqs. thanks!

2018-12-10 21:11 UTC, mdurand42 approved these changes

2018-12-11 01:53 UTC, tdmowrer requested changes

2018-12-11 01:53 UTC, tdmowrer commented on Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs
> +    float coefficientScale = 100.0f;
Needs a public property to avoid warnings in the Editor.

2018-12-11 01:53 UTC, tdmowrer commented on Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs
> +    SkinnedMeshRenderer skinnedMeshRenderer;
Needs a public property to avoid warnings in the Editor.

2018-12-11 01:53 UTC, tdmowrer commented on Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs
> +                if (mappedBlendShapeIndex >= 0 ) {
`{` on a separate line (or just remove it; not required for single line conditionals).

2018-12-11 06:22 UTC, jimmy-jam commented on Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs
> +    SkinnedMeshRenderer skinnedMeshRenderer;
i can provide a default value of null here to get rid of the warning.

2018-12-11 07:28 UTC, jimmy-jam commented on Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs
> +    float coefficientScale = 100.0f;
this does not produce a warning since there is a default value

2018-12-11 18:43 UTC, tdmowrer requested changes

2018-12-11 18:43 UTC, tdmowrer commented on Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs
> +    float coefficientScale = 100.0f;
All `MonoBehaviour`s should be scriptable, which means you should have a public setter. Perhaps we can be more lax with sample code, but I don't see why we shouldn't just give this a public getter/setter.

Also, private fields follow a different naming convention from public properties:
```suggestion
    float m_CoefficientScale = 100.0f;
```

2018-12-11 18:43 UTC, tdmowrer commented on Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs
> +    ARKitFaceSubsystem arkitFaceSubsystem;
```suggestion
    ARKitFaceSubsystem m_ARKitFaceSubsystem;
```

2018-12-11 18:43 UTC, tdmowrer commented on Assets/Scripts/ARFaceArkitBlendShapeVisualizer.cs
> +    SkinnedMeshRenderer skinnedMeshRenderer = null;
```suggestion
    SkinnedMeshRenderer m_SkinnedMeshRenderer;
```

`null` is already the default value here (and explicitly setting it is against our coding convention). Why not give it public accessors?

The setter would also need to regenerate the `m_FaceArkitBlendShapeIndexMap`.

2018-12-11 23:09 UTC, tdmowrer approved these changes

2018-12-13 19:00 UTC, Dianna3D approved these changes
2018.3 and 2019.1 both run, compile and build! 
Theres a prefab issue with 2019.1 (my bug upload was interrupted last night so its resending again now) but after manually adding assets back, everything ran perfectly fine..

QA Approval!

2019-01-10 22:28 UTC, merged